[2015-11-04 12:04:00 +0100] [1804] [INFO] Starting gunicorn 19.3.0
[2015-11-04 12:04:00 +0100] [1804] [INFO] Listening at: http://0.0.0.0:5000 (1804)
[2015-11-04 12:04:00 +0100] [1804] [INFO] Using worker: sync
[2015-11-04 12:04:00 +0100] [1807] [INFO] Booting worker with pid: 1807
[2015-11-04 12:04:00 +0100] [1807] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named 'hello'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named 'hello'
[2015-11-04 12:04:00 +0100] [1807] [INFO] Worker exiting (pid: 1807)
